spring.application.name=stonestorage

# SQL Initialization
spring.sql.init.mode=always

# Database
spring.r2dbc.url=${SPRING_R2DBC_URL}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD}

# Storage provider: local | s3
storage.type=${STORAGE_TYPE}
storage.base-path=${STORAGE_BASE_PATH}

# SpringDoc OpenAPI
springdoc.swagger-ui.enabled=false
springdoc.api-docs.path=/v3/api-docs

spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=20
spring.r2dbc.pool.max-idle-time=3m
spring.r2dbc.pool.max-life-time=15m
spring.r2dbc.pool.validation-query=SELECT 1

server.forward-headers-strategy=framework